package firstheadjava;

public class Cat extends Feline {

    /**
     * 7HENWESAYhYOUMUSTIMPLEMENTTHEABSTRACTMETHODvTHATMEANSYOUMUST
     * PROVIDEABODY4HATMEANSYOUMUSTCREATEANON
     * ABSTRACTMETHODINYOURCLASS
     * WITHTHESAMEMETHODSIGNATURENAMEANDARGUMENTS	ANDARETURNTYPETHATIS
     * COMPATIBLEWITHTHEDECLAREDRETURNTYPEOFTHEABSTRACTMETHOD7HATYOUPUTIN
     * THATMETHODISUPTOYOU!LL*AVACARESABOUTISTHATTHEMETHODISTHEREINYOUR
     * CONCRETESUBCLASS
     */

    @Override
    public void eat() {

        System.out.println("Cat eat. Overridden method.");
    }
}
